name: Install component from local disk

on:
    workflow_dispatch

permissions:
  id-token: write

jobs:
    do-install-local:
        runs-on: ubuntu-latest
        name: Do the install locally
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v6
              with:
                path: ./repo
            - name: Checkout component repo locally
              uses: actions/checkout@v6
              with:
                repository: pierskarsenbarg/storage
                path: ./local-component
            - name: Setup Python
              uses: actions/setup-python@v6
            - name: Install UV
              uses: astral-sh/setup-uv@v7
            - name: Install Pulumi
              uses: pulumi/actions@v6
              with: 
                pulumi-version: "v3.208.0"
            - name: Run pulumi about
              run: pulumi about
              working-directory: ./repo
            - name: Run pulumi install
              run: pulumi install
              working-directory: ./repo
            - name: Pulumi Auth
              uses: pulumi/auth-actions@v1
              with:
                organization: demo
                requested-token-type: urn:pulumi:token-type:access_token:organization
            - name: Pulumi Preview
              run: pulumi preview -s demo/dev
